apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu     
  template:
    metadata:
      labels:
        os: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        command: ["/bin/bash","-c"]
        args: 
          - sleep 300
