apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    nodePort: 30080
    targetPort: "nginx-http"
    name: http
    
