apiVersion: networking.k8s.io/v1
kind: Ingress
ma:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: sanjeebojha.com.np
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port: 
              number: 80
